### ISSUE TITLE
History option throwing a `length` error

### ISSUE THREAD

**Issue by Dawny33** [weslleyaraujo/pirateflix#6]
The `history` option throws the following error:

```
➜  ~ pirateflix --history
/usr/local/lib/node_modules/pirateflix/bin/cli.js:29
      if (!data.history.length) {
                       ^

TypeError: Cannot read property 'length' of undefined
    at /usr/local/lib/node_modules/pirateflix/bin/cli.js:29:24
    at Object.<anonymous> (/usr/local/lib/node_modules/pirateflix/bin/cli.js:51:2)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:146:18)
    at node.js:404:3
```

**Comment by akash0x53** [comment]
Faced the same when .pirateflix file is not present.
